### ISSUE TITLE
Setup initial structure to get device information

### ISSUE THREAD

**Issue by Chesire** [b-reynolds/device-info-app#5]
We need to set up an initial structure in the application, so that it is easy to add more ways to get device information down the line.

We can use this issue to discuss the structure, unless somebody is really sure they have a good way to go about it.

**Comment by Chesire** [comment]
Is it worth just having some classes which produce a `Map<String, String>` as an initial start while somebody gets the initial structure, then we can change these classes to conform to an API? 
The map could just be `info to value` so something like `battery % -> 50%`.

**Comment by ShaunPlummer** [comment]
What does everyone think about using a recycler view and maybe this library? https://github.com/lisawray/groupie

**Comment by Chesire** [comment]
I think using groupie is a good idea, I've created #13 for now so that data can be seen, but I think extending it by using Groupie is a good idea. Will be interesting to see how much difference it makes to a basic adapter

**Comment by Chesire** [comment]
I think this is good to close now @ShaunPlummer? Since we have groupie and its fairly easy to add more data

**Comment by ShaunPlummer** [comment]
Can do, we need to do something with the floating action button but that can be another task.

**Comment by ShaunPlummer** [comment]
I've raised #19.
